import type { ChatCatalogProduct } from "@/types";

// Fictional catalog used only by the public /demo page. No affiliation with
// real brands or SKUs — see DemoDisclaimer for the on-page notice.
function dims(lengthIn: number, widthIn: number, heightIn: number) {
  return `${lengthIn}"L x ${widthIn}"W x ${heightIn}"H`;
}

export const DEMO_CATALOG: ChatCatalogProduct[] = [
  // Sofas
  {
    id: "demo-sofa-modular-haven",
    title: "Modular Haven Sectional",
    category: "Sofas",
    description: "Configurable L-shaped sectional with deep seating, built for family rooms and open-plan living.",
    price: 2499,
    sku: "MOD-SOF-001",
    length: 118,
    width: 72,
    height: 34,
    dimensions: dims(118, 72, 34),
    image: "/images/demo-products/modular-haven-sectional.png",
    colors: ["Ivory", "Slate", "Olive"],
    materials: ["Linen", "Velvet", "Performance Fabric"],
    tags: ["sectional", "large", "living room"],
  },
  {
    id: "demo-sofa-harbor-linen",
    title: "Harbor Linen Sofa",
    category: "Sofas",
    description: "Tailored three-seat sofa with stain-resistant upholstery and compact proportions.",
    price: 1599,
    sku: "MOD-SOF-003",
    length: 88,
    width: 38,
    height: 33,
    dimensions: dims(88, 38, 33),
    image: "/images/demo-products/harbor-linen-sofa.png",
    colors: ["Sand", "Navy", "Charcoal"],
    materials: ["Linen", "Performance Fabric"],
    tags: ["sofa", "compact", "three-seat"],
  },
  {
    id: "demo-sofa-harbor-loveseat",
    title: "Harbor Linen Loveseat",
    category: "Sofas",
    description: "The two-seat companion to the Harbor Linen Sofa, for smaller rooms or paired seating.",
    price: 1199,
    sku: "MOD-SOF-003-LS",
    length: 62,
    width: 38,
    height: 33,
    dimensions: dims(62, 38, 33),
    image: "/images/sofas.png",
    colors: ["Sand", "Navy", "Charcoal"],
    materials: ["Linen", "Performance Fabric"],
    tags: ["loveseat", "small", "compact"],
  },
  {
    id: "demo-sofa-wren-sleeper",
    title: "Wren Sleeper Sofa",
    category: "Sofas",
    description: "Three-seat sofa with a pull-out queen sleeper mechanism for guest rooms and studios.",
    price: 1899,
    sku: "MOD-SOF-004",
    length: 84,
    width: 38,
    height: 35,
    dimensions: dims(84, 38, 35),
    image: "/images/sofas.png",
    colors: ["Oatmeal", "Charcoal"],
    materials: ["Performance Fabric"],
    tags: ["sleeper", "guest room"],
  },
  {
    id: "demo-sofa-bellamy-leather",
    title: "Bellamy Leather Sofa",
    category: "Sofas",
    description: "Full-grain leather three-seat sofa with a low, modern profile.",
    price: 2299,
    sku: "MOD-SOF-005",
    length: 90,
    width: 39,
    height: 33,
    dimensions: dims(90, 39, 33),
    image: "/images/sofas.png",
    colors: ["Cognac", "Espresso"],
    materials: ["Leather"],
    tags: ["leather", "sofa"],
  },

  // Beds
  {
    id: "demo-bed-cloud-storage-queen",
    title: "Cloud Storage Bed (Queen)",
    category: "Beds",
    description: "Platform bed with concealed drawer storage and a soft upholstered headboard.",
    price: 1899,
    sku: "MOD-BED-004-Q",
    length: 84,
    width: 66,
    height: 48,
    dimensions: dims(84, 66, 48),
    image: "/images/demo-products/cloud-storage-bed.png",
    colors: ["Mist", "Oat", "Graphite"],
    materials: ["Performance Fabric", "Oak Veneer"],
    tags: ["bed", "storage", "queen"],
  },
  {
    id: "demo-bed-nordic-platform-queen",
    title: "Nordic Platform Bed (Queen)",
    category: "Beds",
    description: "Minimal bed frame with clean lines and warm wood construction.",
    price: 1299,
    sku: "MOD-BED-009-Q",
    length: 82,
    width: 64,
    height: 38,
    dimensions: dims(82, 64, 38),
    image: "/images/demo-products/nordic-platform-bed.png",
    colors: ["Natural Oak", "Walnut"],
    materials: ["Solid Wood"],
    tags: ["bed", "platform", "queen"],
  },
  {
    id: "demo-bed-nordic-platform-king",
    title: "Nordic Platform Bed (King)",
    category: "Beds",
    description: "The king-size version of the Nordic Platform Bed, same minimal frame with a wider base.",
    price: 1499,
    sku: "MOD-BED-009-K",
    length: 82,
    width: 80,
    height: 38,
    dimensions: dims(82, 80, 38),
    image: "/images/demo-products/nordic-platform-bed.png",
    colors: ["Natural Oak", "Walnut"],
    materials: ["Solid Wood"],
    tags: ["bed", "platform", "king"],
  },
  {
    id: "demo-bed-sawyer-upholstered-queen",
    title: "Sawyer Upholstered Bed (Queen)",
    category: "Beds",
    description: "Upholstered bed with a tall channel-tufted headboard.",
    price: 1699,
    sku: "MOD-BED-006-Q",
    length: 88,
    width: 65,
    height: 48,
    dimensions: dims(88, 65, 48),
    image: "/images/beds.png",
    colors: ["Dove", "Charcoal"],
    materials: ["Performance Fabric"],
    tags: ["bed", "upholstered", "queen"],
  },
  {
    id: "demo-bed-rowe-canopy-king",
    title: "Rowe Canopy Bed (King)",
    category: "Beds",
    description: "Four-post canopy bed frame in solid wood, king size.",
    price: 2399,
    sku: "MOD-BED-007-K",
    length: 87,
    width: 81,
    height: 84,
    dimensions: dims(87, 81, 84),
    image: "/images/beds.png",
    colors: ["Walnut", "Black Oak"],
    materials: ["Solid Wood"],
    tags: ["bed", "canopy", "king"],
  },

  // Dining
  {
    id: "demo-dining-walnut-gathering-set",
    title: "Walnut Gathering Dining Set",
    category: "Dining sets",
    description: "Six-seat dining set with a rounded walnut table and upholstered side chairs.",
    price: 3299,
    sku: "MOD-DIN-005",
    length: 96,
    width: 42,
    height: 30,
    dimensions: dims(96, 42, 30),
    image: "/images/demo-products/walnut-gathering-dining-set.png",
    colors: ["Walnut", "Black", "Cream"],
    materials: ["Solid Wood", "Boucle", "Brass"],
    tags: ["dining", "seats 6", "table set"],
  },
  {
    id: "demo-dining-heritage-chair",
    title: "Heritage Upholstered Dining Chair",
    category: "Dining sets",
    description: "Durable dining chair with contract-grade upholstery and a curved back.",
    price: 349,
    sku: "MOD-DIN-013",
    length: 24,
    width: 22,
    height: 34,
    dimensions: dims(24, 22, 34),
    image: "/images/demo-products/heritage-upholstered-dining-chair.png",
    colors: ["Dove", "Moss", "Cognac"],
    materials: ["Velvet", "Performance Fabric", "Solid Wood"],
    tags: ["dining chair"],
  },
  {
    id: "demo-dining-marin-round-table",
    title: "Marin Round Dining Table",
    category: "Dining sets",
    description: "Round dining table seating four, in solid oak.",
    price: 1099,
    sku: "MOD-DIN-010",
    length: 48,
    width: 48,
    height: 30,
    dimensions: `48" diameter x 30"H`,
    image: "/images/dining-sets.png",
    colors: ["Natural Oak"],
    materials: ["Solid Wood"],
    tags: ["dining", "round", "seats 4"],
  },
  {
    id: "demo-dining-oakhurst-bench",
    title: "Oakhurst Dining Bench",
    category: "Dining sets",
    description: "Backless dining bench in solid oak, pairs with the Marin or Walnut Gathering tables.",
    price: 499,
    sku: "MOD-DIN-011",
    length: 60,
    width: 15,
    height: 18,
    dimensions: dims(60, 15, 18),
    image: "/images/dining-sets.png",
    colors: ["Natural Oak", "Walnut"],
    materials: ["Solid Wood"],
    tags: ["dining", "bench"],
  },
  {
    id: "demo-dining-reeve-extension-table",
    title: "Reeve Extension Dining Table",
    category: "Dining sets",
    description: "Extendable dining table, seats 6 closed or 8 with the leaf inserted.",
    price: 2199,
    sku: "MOD-DIN-012",
    length: 96,
    width: 42,
    height: 30,
    dimensions: `72"-96"L (with leaf) x 42"W x 30"H`,
    image: "/images/dining-sets.png",
    colors: ["Walnut", "Natural Oak"],
    materials: ["Solid Wood"],
    tags: ["dining", "extension", "seats 8"],
  },

  // Storage
  {
    id: "demo-storage-atelier-media-console",
    title: "Atelier Media Console",
    category: "Storage",
    description: "Low media storage console with fluted doors and cable-management pass-throughs.",
    price: 1199,
    sku: "MOD-STO-006",
    length: 72,
    width: 18,
    height: 28,
    dimensions: dims(72, 18, 28),
    image: "/images/demo-products/atelier-media-console.png",
    colors: ["Oak", "Walnut", "Matte Black"],
    materials: ["Solid Wood", "MDF", "Metal"],
    tags: ["storage", "media console"],
  },
  {
    id: "demo-storage-rattan-accent-cabinet",
    title: "Rattan Accent Cabinet",
    category: "Storage",
    description: "Two-door accent storage cabinet with woven rattan panels and rounded pulls.",
    price: 749,
    sku: "MOD-STO-010",
    length: 36,
    width: 18,
    height: 34,
    dimensions: dims(36, 18, 34),
    image: "/images/demo-products/rattan-accent-cabinet.png",
    colors: ["Natural", "Black"],
    materials: ["Rattan", "Oak Veneer"],
    tags: ["storage", "cabinet"],
  },
  {
    id: "demo-storage-linden-sideboard-narrow",
    title: "Linden Sideboard (Narrow)",
    category: "Storage",
    description: "Two-door sideboard sized for narrow walls and small dining rooms.",
    price: 1199,
    sku: "MOD-STO-020-N",
    length: 47,
    width: 18,
    height: 32,
    dimensions: dims(47, 18, 32),
    image: "/images/storage.png",
    colors: ["Walnut", "White Oak"],
    materials: ["Solid Wood"],
    tags: ["storage", "sideboard", "narrow"],
  },
  {
    id: "demo-storage-linden-sideboard-wide",
    title: "Linden Sideboard (Wide)",
    category: "Storage",
    description: "Four-door sideboard with the most storage that still fits most standard dining walls.",
    price: 1699,
    sku: "MOD-STO-020-W",
    length: 71,
    width: 19,
    height: 32,
    dimensions: dims(71, 19, 32),
    image: "/images/storage.png",
    colors: ["Walnut", "White Oak"],
    materials: ["Solid Wood"],
    tags: ["storage", "sideboard", "wide"],
  },
  {
    id: "demo-storage-linden-sideboard-xwide",
    title: "Linden Sideboard (Extra-Wide)",
    category: "Storage",
    description: "The largest sideboard in the Linden line, for great rooms and long dining walls.",
    price: 2199,
    sku: "MOD-STO-020-XW",
    length: 84,
    width: 20,
    height: 34,
    dimensions: dims(84, 20, 34),
    image: "/images/storage.png",
    colors: ["Walnut", "White Oak"],
    materials: ["Solid Wood"],
    tags: ["storage", "sideboard", "extra wide", "large"],
  },
];

export type DemoRoomPhoto = {
  id: string;
  label: string;
  src: string;
  prompt: string;
};

// Sample rooms visitors can use instead of uploading their own photo.
// Dimensions are fictional labels attached to stock interior photos so the
// assistant has something concrete to reason about.
export const DEMO_ROOM_PHOTOS: DemoRoomPhoto[] = [
  {
    id: "living-room",
    label: "Living room, 12 x 14 ft",
    src: "/images/living-room-hero.png",
    prompt: "Here's a photo of my living room, about 12 by 14 ft.",
  },
  {
    id: "family-room",
    label: "Family room, 14 x 16 ft",
    src: "/images/origin-room.jpg",
    prompt: "Here's a photo of my family room, about 14 by 16 ft.",
  },
  {
    id: "dining-room",
    label: "Dining room, 10 x 12 ft",
    src: "/images/walnut-dining-room-demo.png",
    prompt: "Here's a photo of my dining room, about 10 by 12 ft, with an 8 ft wall I'd like to put a sideboard against.",
  },
];

export const DEMO_SUGGESTED_PROMPTS: string[] = [
  "Will the Modular Haven Sectional fit a 12 by 14 living room?",
  "What is the widest sideboard that fits a 2m wall?",
  "Show me something similar but smaller.",
  "I need a dining set that seats 6.",
];
