import { i } from '@instantdb/core'

const schema = i.schema({
  entities: {
    users: i.entity({
      name: i.any(),
      email: i.any(),
      password: i.any(),
      createdAt: i.any(),
    }),
    stores: i.entity({
      name: i.any(),
      apiKey: i.any(),
      userId: i.any(),
      storeUrl: i.any(),
      url: i.any(),
      supportEmail: i.any(),
      widgetTitle: i.any(),
      primaryColor: i.any(),
      welcomeMessage: i.any(),
      enabledActions: i.any(),
      enableViewInCatalog: i.any(),
      enableCustomize: i.any(),
      enableRequestQuote: i.any(),
      quoteEmail: i.any(),
      domain: i.any(),
      platform: i.any(),
      catalogSource: i.any(),
      credentials: i.any(),
      wooKey: i.any(),
      wooSecret: i.any(),
      productCount: i.any(),
      stripeCustomerId: i.any(),
      stripeSubscriptionId: i.any(),
      subscriptionStatus: i.any(),
      subscriptionPlan: i.any(),
      currentPeriodEnd: i.any(),
      trialStartedAt: i.any(),
      trialEndsAt: i.any(),
      aiChatsUsed: i.any(),
      roomPlannerAnalysesUsed: i.any(),
      setupComplete: i.any(),
      shopifyStoreDomain: i.any(),
      shopifyAccessToken: i.any(),
      shopifyConnectedAt: i.any(),
      shopifyLastSyncedAt: i.any(),
      lastSyncAt: i.any(),
      lastSyncedAt: i.any(),
      createdAt: i.any(),
      updatedAt: i.any(),
    }),
    products: i.entity({
      storeId: i.any(),
      title: i.any(),
      name: i.any(),
      price: i.any(),
      description: i.any(),
      image: i.any(),
      imageUrl: i.any(),
      category: i.any(),
      source: i.any(),
      externalId: i.any(),
      handle: i.any(),
      productUrl: i.any(),
      url: i.any(),
      sku: i.any(),
      status: i.any(),
      length: i.any(),
      width: i.any(),
      height: i.any(),
      colors: i.any(),
      materials: i.any(),
      createdAt: i.any(),
      updatedAt: i.any(),
    }),
    syncEvents: i.entity({
      storeId: i.any(),
      type: i.any(),
      productCount: i.any(),
      status: i.any(),
      createdAt: i.any(),
    }),
    events: i.entity({
      storeId: i.any(),
      type: i.any(),
      metadata: i.any(),
      createdAt: i.any(),
    }),
  },
  links: {
    storeUser: {
      forward: { on: 'stores', has: 'one', label: 'user' },
      reverse: { on: 'users', has: 'one', label: 'store' },
    },
    storesProducts: {
      forward: { on: 'stores', has: 'many', label: 'products' },
      reverse: { on: 'products', has: 'one', label: 'store' },
    },
    storesEvents: {
      forward: { on: 'stores', has: 'many', label: 'events' },
      reverse: { on: 'events', has: 'one', label: 'store' },
    },
  },
})

export default schema
